name: Advanced Inventory CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h localhost -p${{ secrets.DB_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      - name: Create .env File
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> Backend/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> Backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> Backend/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> Backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> Backend/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> Backend/.env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> Backend/.env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" >> Backend/.env
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> Backend/.env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> Backend/.env
          echo "ADMIN_ROLE=${{ secrets.ADMIN_ROLE }}" >> Backend/.env

      - name: Create Database Tables
        working-directory: Backend
        run: python create_sqltables.py

      - name: Create Admin User
        working-directory: Backend
        run: python create_admin.py

      - name: Run Tests
        working-directory: Backend
        run: pytest -v